### ISSUE TITLE
when not login any user, Click the Workload show error "TypeError in Work_load#show "

### ISSUE THREAD

**Issue by archonwang** [dnoise/Redmine-Wordkload-Dnoise#1]
HI, the steps as follows:
1. open redmine
2. then Click the Workload
3. Error message like this :

TypeError in Work_load#show

Showing vendor/plugins/redmine_dnoise_workload/app/views/work_load/show.html.erb where line #215 raised:

nil can't be coerced into Fixnum

Extracted source (around line #215):

212:                                    </div>
213:  
214:                                        <%
215:                                        remanentes_by_user[user.id] = @utils.getRemanente(user.id, @fecha_actual)
216:                                        issues_remanentes_by_user[user.id] = @utils.getIssuesOpenedWihtout(user.id, @gantt.date_from)
217:                                        %>
218:                                        

RAILS_ROOT: D:/redmine
Application Trace | Framework Trace | Full Trace

D:/redmine/vendor/plugins/redmine_dnoise_workload/lib/list_user.rb:16:in `+'
D:/redmine/vendor/plugins/redmine_dnoise_workload/lib/list_user.rb:16:in`getRemanente'
D:/redmine/vendor/plugins/redmine_dnoise_workload/lib/list_user.rb:15:in `each'
D:/redmine/vendor/plugins/redmine_dnoise_workload/lib/list_user.rb:15:in`getRemanente'
D:/redmine/vendor/plugins/redmine_dnoise_workload/app/views/work_load/show.html.erb:215:in `_run_erb_vendor47plugins47redmine_dnoise_workload47app47views47work_load47show46html46erb'
D:1:in`each'
D:1:in `__send__'
D:1:in`each'

Request

Parameters:

{"month"=>7,
 "year"=>2011,
 "months"=>6,
 "show_issues"=>"1"}

Show session dump
Response

Headers:

{"Content-Type"=>"text/html",
 "Cache-Control"=>"no-cache"}

**Comment by dnoise** [comment]
Tx for the info... we will try to improve plug as soon as our workload allow us :)

**Comment by javierpadin20** [comment]
Hi, i've the same problem. Did you resolve it? Tx!!
