### ISSUE TITLE
ActionView::TemplateError (divided by 0) on line #226

### ISSUE THREAD

**Issue by camilonova** [dnoise/Redmine-Wordkload-Dnoise#7]
I have this:

```
Redmine 1.2.1.stable
```

and i get this error:

``` ruby
Processing WorkLoadController#show (for 190.147.153.XXX at 2011-08-24 11:01:50) [GET]
  Parameters: {"action"=>"show", "controller"=>"work_load"}
Rendering template within layouts/base
Rendering work_load/show

ActionView::TemplateError (divided by 0) on line #226 of vendor/plugins/redmine_dnoise_workload/app/views/work_load/show.html.erb:
223:                                        sum = 0
224:                                        TimeEntry.find(:all, :conditions => ["issue_id = #{issue.id}"]).each do |h| sum+=h.hours end
225:                                        total_rem_by_user[user.id] = sum
226:                                        calculos[issue.id] = CalculosTareas.new(issue.id, issue.start_date, issue.due_date, issue.estimated_hours, sum, issue.done_ratio, issue.priority_id, @fecha_actual, @utils.issue_is_parent(issue) )
227:                                        workload_by_user[user.id].push(calculos[issue.id].dias_y_time_restantes)
228:                                        len = 37 - ( issue.id.to_s.length - 1 )
229:                                        if (params[:show_issues] == "1") then %>

    vendor/plugins/redmine_dnoise_workload/app/views/work_load/show.html.erb:226:in `new'
    vendor/plugins/redmine_dnoise_workload/app/views/work_load/show.html.erb:226
    vendor/plugins/redmine_dnoise_workload/app/views/work_load/show.html.erb:221:in `each'
    vendor/plugins/redmine_dnoise_workload/app/views/work_load/show.html.erb:221
    vendor/plugins/redmine_dnoise_workload/app/views/work_load/show.html.erb:205
    passenger (3.0.2) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
    passenger (3.0.2) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
    passenger (3.0.2) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
    passenger (3.0.2) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
    passenger (3.0.2) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
    passenger (3.0.2) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
    passenger (3.0.2) lib/phusion_passenger/utils.rb:479:in `safe_fork'
    passenger (3.0.2) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
    passenger (3.0.2) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
    passenger (3.0.2) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
    passenger (3.0.2) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
    passenger (3.0.2) lib/phusion_passenger/abstract_server.rb:180:in `start'
    passenger (3.0.2) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
    passenger (3.0.2) lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
    passenger (3.0.2) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
    passenger (3.0.2) lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
    passenger (3.0.2) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
    passenger (3.0.2) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
    passenger (3.0.2) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
    passenger (3.0.2) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
    passenger (3.0.2) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
    passenger (3.0.2) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
    passenger (3.0.2) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
    passenger (3.0.2) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
    passenger (3.0.2) helper-scripts/passenger-spawn-server:99

Rendering /opt/redmine/public/500.html (500 Internal Server Error)
```

**Comment by dnoise** [comment]
We are on hollidays, but we will be back soon :)

(ty)

**Comment by camilonova** [comment]
still on holidays?

**Comment by dnoise** [comment]
Hi, we are working, but still in other client projects. We will try to upgrade as often as we can, but we have a copuple of projects finishing.

sory for the inconvenience

**Comment by dnoise** [comment]
Sory for closing ;)

**Comment by camilonova** [comment]
Dude, this is the main problem of open source projects.

**Comment by dnoise** [comment]
For sure, we have a brutal workload nowadays... patience :((
